from enum import Enum


class AuditEvent(str, Enum):
    USER_CREATED = "USER_CREATED"
    LOGIN = "LOGIN"
    REPORT_CREATED = "REPORT_CREATED"
    REPORT_UPDATED = "REPORT_UPDATED"
    REPORT_ASSIGNED = "REPORT_ASSIGNED"
    REPORT_COMPLETED = "REPORT_COMPLETED"